### ISSUE TITLE
cant craft armor

### ISSUE THREAD

**Issue by RyanCR03** [MelanX/MoreVanillaArmor#1]

**Comment by MelanX** [comment]
Which type?
Which items did you try?
Did you look at the recipe with JEI?
Please provide more information.

**Comment by MelanX** [comment]
I had a look with JEI and every item has the right recipe.

**Comment by RyanCR03** [comment]
i tried lapis and redstone and had no JEI, i used the recipe book. it doesnt show a recipe.

**Comment by MelanX** [comment]
Lapis, Redstone, Coal, Quartz and Glowstone require blocks. If this fixes you problem, let me know.
If it doesn't, please give versions (mc, mod and forge)
