### ISSUE TITLE
The mod isn't suited for servers, it crashes them because it assumes it is on the client side

### ISSUE THREAD

**Issue by AJMC2002** [MelanX/MoreVanillaArmor#14]
The mod returns an error message when used for a server, it'd be really helpful to make it able to run on servers.

> Mod File: morevanillaarmor-1.16.4-1.2.4.jar
> 	Failure message: MoreVanillaArmor (morevanillaarmor) encountered an error during the load_registries event phase
> 		java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER
> 	Mod Version: 1.16.4-1.2.4
> 	Mod Issue URL: NOT PROVIDED
> 	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/entity/player/ClientPlayerEntity for invalid dist DEDICATED_SERVER

**Comment by MelanX** [comment]
Already fixed, update the mod
