### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/MoreVanillaArmor#15]
I want to change to license from MIT License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [x] @draklorx 
- [x] @TheDirectorX 
- [x] d3ath9un (Discord)

**Comment by draklorx** [comment]
All good from me!

**Comment by TheDirectorX** [comment]
https://github.com/MelanX/MoreVanillaTools/issues/28#issuecomment-922494947

**Comment by MelanX** [comment]
https://github.com/MelanX/MoreVanillaArmor/commit/7249646a9ad841cfaa86a19ff6bbb3f9327a047e
