### ISSUE TITLE
Not loading...

### ISSUE THREAD

**Issue by antiwesley** [MelanX/MoreVanillaArmor#17]
### Minecraft version

1.19

### MoreVanillaArmor version

1.19-4.0.2

### Forge version

41.0.98

### The latest.log file

https://pastebin.com/Nn6CA3T4

### Issue description

Mod refuses to load; see attached crash report. 

### Steps to reproduce

1. Put mod in mods folder.
2. start up game
3. load game
4. read the error message that halts the game
5. copy error log 
6. submit to the awesome developer.

**Comment by antiwesley** [comment]
I'll add that all the other awesome MoreVanilla mods work just fine. Just Armor is borking out

**Comment by MelanX** [comment]
Oh, yes. Forgot to fix it after the second breaking forge version. Thank you for the reminder!
