### ISSUE TITLE
Possible Mod Conflicts or Mod Crashing

### ISSUE THREAD

**Issue by Camawama** [MelanX/MoreVanillaArmor#2]
Hey there, my name is Alex and I have been trying to put together this Modpack for me and some friends to play on. Your mod works perfectly fine client-side but when running on a server it crashes and doesn't even load the world (like a few other mods I tried installing. I have put together a ZIP file with the Logs, Crash report, and other mods installed with it. I did this for every mod that caused the server to crash and I am contacting developers of the mods in hopes that it's enough information to diagnose the problems. I love to discover bugs and report them so if you ever need some help my discord is Cama#6274

Forge Version: Forge-30.0.39
Minecraft Version: 1.15.1

Here is the link: http://www.mediafire.com/file/9286odql5lqahun/More_Vanilla_Armor.zip/file

**Comment by MelanX** [comment]
Downloaded the MoreVanillaTools file. Because this should be the same I know that this mod is not the reason.

**Comment by MelanX** [comment]
https://pastebin.com/9Jp3Pg4D
