### ISSUE TITLE
About fabric.

### ISSUE THREAD

**Issue by jaumdomine** [MelanX/MoreVanillaArmor#20]
### Describe your idea

I'm a minecraft player, however, I have a weak pc and I use sodium (a fabric mod, it helps a lot with fps) but I can't use sodium in forge, I wish they would release the mod for the fabric version (1.20.1) The mod is amazing, complete and with great armor models. (I'm sure I'm not the only one looking for a fabric version)

**Comment by MelanX** [comment]
If anyone wants to port it to fabric, they may do it. I'm creating Forge mods, not Fabric mods. 
And here's an unofficial fork of Sodium for Forge: 
- https://modrinth.com/mod/rubidium
- https://www.curseforge.com/minecraft/mc-mods/rubidium
