### ISSUE TITLE
Lightning Magnet set bonus works with every armor set

### ISSUE THREAD

**Issue by gregoryeple** [MelanX/MoreVanillaArmor#21]
**Version**
`MoreVanillaArmor-1.19.1-4.1.1`

**All armor sets act as a lightning magnet instead of just the copper one.**

The problem seems to come from the file [Events.java](https://github.com/MelanX/MoreVanillaArmor/blob/62f2f17823824212cd67a2f89266c8aa12c699bb/src/main/java/de/melanx/MoreVanillaArmor/Events.java#L36C20-L36C20)
```
// Current code
.filter(livingEntity -> Armor.getArmorSetType(livingEntity) != null)
```
```
// Suggested change
.filter(livingEntity -> Armor.getArmorSetType(livingEntity) == ArmorTiers.COPPER)
```

**Comment by MelanX** [comment]
Thank you very much!

**Comment by gregoryeple** [comment]
I Just checked the commits, doesn't it make it apply to every armor set **except** the copper one?

```
// For reference, the code in the commits
.filter(livingEntity -> Armor.getArmorSetType(livingEntity) != ArmorTiers.COPPER)
```

**Comment by MelanX** [comment]
Oof you’re right… will fix it tomorrow.
