### ISSUE TITLE
[1.15.2] Error during the load_registries event phase: ITEM_ARMOR_EQUIP_ELYTRA

### ISSUE THREAD

**Issue by realTIMematrix** [MelanX/MoreVanillaArmor#3]
Hi,

got issue while loading:

Using only this, no other mods.
- Minecraft 1.15.2
- Forge 31.0.1
- morevanillaarmor-1.15.2-1.1.1.jar

Log: [latest.log](https://pastebin.com/6zW8zbGA) 

Debug: [debug.log](https://pastebin.com/QpxGNFb8)

**Comment by MelanX** [comment]
Fixed and new version is available now. Deleted the old one because it was just a compiling mistake.
