### ISSUE TITLE
Remove tags because of issues

### ISSUE THREAD

**Issue by Marcinosoft** [MelanX/MoreVanillaArmor#9]
Hi. Mod works fine in singleplayer mode, but connecting to Spigot server v1.16.3 cause "Connection Lost. Incomplete set of tags received from server. Please contact server operator" .
So it makes impossible to play in multiplayer mode, at least on Spigot server. May it be Spigot or Forge issue?

Here is error message at client side:

[Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Incomplete server tags, disconnecting. Missing: {minecraft:item=[forge:prismarine, forge:netherbricks, forge:paper, forge:magma_block, forge:slime_block, forge:storage_blocks/glowstone]}

At Spigot server side:

[Server thread/INFO]: Player logged in with entity id 123 at ([world]-81.539669578709553, 76.0, -1429.6474654802346)
[Server thread/INFO]: Player lost connection: Disconnected
[Server thread/INFO]: Player left the game

Game version: 1.16.3-forge-34.0.0
Mod file: morevanillaarmor-1.16.2-1.2.jar  (MD5: 3199aac3a141b66bd74d03360a1ec756)
Spigot version: 1.16.3-R0.1-SNAPSHOT

**Comment by MelanX** [comment]
Without spigot everything is fine. I never used spigot and I have no idea how it works but without spigot, everything is fine, so I think it’s not my mods fault.

**Comment by Marcinosoft** [comment]
Yes, It works fine in sigleplayer mode, but if players have to turn this mod off before play online it's kinda unuseable. I'll try to check if it works with Paper in the meantime.

**Comment by MelanX** [comment]
It would be every mod which adds tags. The tags are missing on server if the server doesn’t have these tags registered. That should happen with every mod which adds new tags.

**Comment by vinnyg0621** [comment]
can someone help me? I'm having the same problem but I don't know what anyone means. can someone send me a video?

**Comment by Marcinosoft** [comment]
Unfortunatelly same issue on Paper :(
Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Comment by MelanX** [comment]
It’s because you need to register the tags on server, too. Tags are server side.
I think I will release a version of the mod which doesn’t add any tags. But I need to look more at the mod and at the moment other stuff has priority.

**Comment by Marcinosoft** [comment]
Well, if you know how to add new tags at server side for Spigot or better Paper it may be solution for server owners, but of course it will not cover other's servers. It would be great to somehow identify within the code if user is connected to internal server (singeplayer mode) or external server (multiplayer), to do not request additional tags or simply disable whole mod at all if there is no simple solution. Thanks.
